# Generated by Django 5.1.1 on 2024-12-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valutak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penznem', models.CharField(max_length=100)),
                ('arfolyam', models.FloatField()),
            ],
        ),
    ]
