# Generated by Django 5.1.2 on 2024-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valutak',
            name='penznemhosszan',
            field=models.CharField(default='Penznemhosszan', max_length=100),
        ),
    ]
