# Generated by Django 5.1.4 on 2025-01-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0003_remove_valutak_penznemhosszan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValutaNevek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutanevek', models.CharField(max_length=100)),
            ],
        ),
    ]
