# Generated by Django 5.1.4 on 2025-01-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0004_valutanevek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValutaNevek',
        ),
        migrations.AddField(
            model_name='valutak',
            name='valutanevek',
            field=models.CharField(default='   ', max_length=100),
        ),
    ]
