# Generated by Django 5.1.4 on 2025-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0005_delete_valutanevek_valutak_valutanevek'),
    ]

    operations = [
        migrations.CreateModel(
            name='mnb_deviza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Valuta',
            },
        ),
    ]
