# Generated by Django 5.1.4 on 2025-01-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0006_mnb_deviza'),
    ]

    operations = [
        migrations.CreateModel(
            name='mnb_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallname', models.CharField(max_length=5)),
                ('longname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'deviza neve',
            },
        ),
    ]
