# Generated by Django 5.1.4 on 2025-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0007_mnb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='mnb_name_good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('longname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'deviza neve',
            },
        ),
    ]
