# Generated by Django 5.1.4 on 2025-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0008_mnb_name_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnb_name_good',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
