# Generated by Django 5.1.4 on 2025-01-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penzvalto', '0009_mnb_name_good_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnb_name',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
